# ^ and _ are converted to superscript and subscript in forms and reports.
Units =
  $m2: '$/m^2'
  $: '$'
  $day: '$/day'
  $kWh: '$/kWh'
  $MJ: '$/MJ'
  $kL: '$/kL'
  co2: 'kg CO_2-e'
  co2kWh: 'kg CO_2-e/kWh'
  co2m2year: 'kg CO_2-e/m^2/year'
  co2year: 'kg CO_2-e/year'
  co2GJ: 'kg CO_2-e/GJ'
  deg: 'degrees'
  GJ: 'GJ'
  GJm2: 'GJ/m2'
  GJm2year: 'GJ/m2/year'
  GJyear: 'GJ/year'
  GJyearOccupant: 'GJ/year/occupant'
  ha: 'ha'
  jobs: 'jobs'
  kgco2: 'kg CO_2-e'
  kgco2day: 'kg CO_2-e/day'
  kgco2kWh: 'kg CO_2-e/kWh'
  kgco2km: 'kg CO_2-e/km'
  kgco2m2: 'kg CO_2-e/m^2'
  kgco2year: 'kg CO_2-e/year'
  kW: 'kW'
  kWh: 'kWh'
  kWhday: 'kWh/day'
  kWhyear: 'kWh/year'
  kLyear: 'kL/year'
  kLyearOccupant: 'kL/year/occupant'
  kLm2year: 'kL/m^2/year'
  km: 'km'
  kmday: 'km/day'
  kmyear: 'km/year'
  lanes: 'lanes'
  Lsec: 'L/second'
  Lyear: 'L/year'
  m: 'm'
  m2: 'm^2'
  m2vehicle: 'm^2/vehicle'
  m2job: 'm^2/job'
  mm: 'mm'
  MLyear: 'ML/year'
  MJ: 'MJ'
  MJm2year: 'MJ/m^2/year'
  MJyear: 'MJ/year'
  people: 'people'
  spaces: 'spaces'
  spacesm: 'spaces/m'
  tripsday: 'trips/day'
  tripsyear: 'trips/year'
  vehicles: 'vehicles'
  years: 'years'

Depends.define 'Units', Units
